version: "3"
services:
  influxdb-1:
    container_name: influxdb-1
    image: influxdb:2.7
    ports:
      - "8087:8087"
    command: influxd --http-bind-address=:8087
    volumes:
      - ./influxdb-1/data:/var/lib/influxdb2
      - ./influxdb-1/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=leduclong
      - DOCKER_INFLUXDB_INIT_PASSWORD=leduclong
      - DOCKER_INFLUXDB_INIT_ORG=longgroup
      - DOCKER_INFLUXDB_INIT_BUCKET=longbucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-token
  influxdb-2:
    container_name: influxdb-2
    image: influxdb:2.7
    ports:
      - "8088:8088"
    command: influxd --http-bind-address=:8088
    volumes:
      - ./influxdb-2/data:/var/lib/influxdb2
      - ./influxdb-2/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=leduclong
      - DOCKER_INFLUXDB_INIT_PASSWORD=leduclong
      - DOCKER_INFLUXDB_INIT_ORG=longgroup
      - DOCKER_INFLUXDB_INIT_BUCKET=longbucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-token
  influxdb-3:
    container_name: influxdb-3
    image: influxdb:2.7
    ports:
      - "8089:8089"
    command: influxd --http-bind-address=:8089
    volumes:
      - ./influxdb-3/data:/var/lib/influxdb2
      - ./influxdb-3/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=leduclong
      - DOCKER_INFLUXDB_INIT_PASSWORD=leduclong
      - DOCKER_INFLUXDB_INIT_ORG=longgroup
      - DOCKER_INFLUXDB_INIT_BUCKET=longbucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-token
  app-1:
    container_name: app-1
    build: .
    environment:
      - PORT=3001
      - NAME=Server1
      - INFLUXDB=influxdb-1
      - INFLUXDB_PORT=8087
    ports:
      - "3001:3001"
    depends_on:
      - influxdb-1
    volumes:
      - ./app:/app
  app-2:
    container_name: app-2
    build: .
    environment:
      - PORT=3002
      - NAME=Server2
      - INFLUXDB=influxdb-2
      - INFLUXDB_PORT=8088
    ports:
      - "3002:3002"
    depends_on:
      - influxdb-2
    volumes:
      - ./app:/app
  app-3:
    container_name: app-3
    build: .
    environment:
      - PORT=3003
      - NAME=Server3
      - INFLUXDB=influxdb-3
      - INFLUXDB_PORT=8089
    ports:
      - "3003:3003"
    depends_on:
      - influxdb-3
    volumes:
      - ./app:/app
  nginx:
    container_name: nginx
    image: nginx:1.28.0
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app-1
      - app-2
      - app-3
  api:
    container_name: api
    build: ./api
    environment:
      - PORT=3004
    ports:
      - "3004:3004"
    depends_on:
      - nginx
    volumes:
      - ./api:/app
  view:
    container_name: view
    build: ./view
    environment:
      - PORT=3005
    ports:
      - "3005:3005"
    depends_on:
      - nginx
    volumes:
      - ./view:/app
  request:
    container_name: request
    build: ./request
    environment:
      - PORT=3006
    ports:
      - "3006:3006"
    depends_on:
      - nginx
    volumes:
      - ./request:/app
